# Generated by Django 5.2.1 on 2025-10-16 06:31

import mainz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/xlsx/', validators=[mainz.models.validate_xlsx])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(choices=[('bid', 'Bid'), ('trip', 'Trip'), ('subscription', 'Subscription'), ('sfq', 'SFQ'), ('driver', 'Driver')], max_length=50)),
            ],
        ),
    ]
