# Generated by Django 5.2.1 on 2025-10-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainz', '0002_alter_tripdataupload_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdataupload',
            name='file_type',
            field=models.CharField(choices=[('bid', 'Bid'), ('trip', 'Trip'), ('subscription', 'Subscription'), ('sfq', 'SFQ'), ('driver', 'Driver'), ('testdata', 'TestData'), ('location', 'Location')], max_length=50),
        ),
    ]
